### ISSUE TITLE
ThCudaCheck: out of memory

### ISSUE THREAD

**Issue by khaulahzia** [phillipi/pix2pix#107]
while i run the training command:
DATA_ROOT=./datasets/alphabet1 name=blob_placement1 which_direction=AtoB th train.lua
I get the following output:
{
  cudnn : 1
  name : "blob_placement1"
  niter : 200
  batchSize : 1
  n_layers_D : 0
  ndf : 64
  which_model_netG : "unet"
  save_display_freq : 5000
  print_freq : 50
  gpu : 1
  use_GAN : 1
  DATA_ROOT : "./datasets/alphabet1"
  serial_batch_iter : 1
  use_L1 : 1
  save_epoch_freq : 50
  output_nc : 3
  checkpoints_dir : "./checkpoints"
  input_nc : 3
  beta1 : 0.5
  continue_train : 0
  which_direction : "AtoB"
  phase : "train"
  fineSize : 256
  condition_GAN : 1
  loadSize : 286
  lambda : 100
  ngf : 64
  preprocess : "regular"
  which_model_netD : "basic"
  display : 1
  display_freq : 100
  display_id : 10
  flip : 1
  ntrain : inf
  lr : 0.0002
  nThreads : 2
  display_plot : "errL1"
  save_latest_freq : 5000
  serial_batches : 0
}
Random Seed: 3566	
#threads...2	
Starting donkey with id: 1 seed: 3567
table: 0x41eedc58
Starting donkey with id: 2 seed: 3568
table: 0x40b5d2b0
./datasets/alphabet1
./datasets/alphabet1
trainCache	/home/admink/pix2pix/cache/_home_admink_pix2pix_datasets_alphabet1_train_trainCache.t7
Creating train metadata
serial batch:, 	0
table: 0x41177720
running "find" on each class directory, and concatenate all those filenames into a single file containing all image paths for a given class
trainCache	/home/admink/pix2pix/cache/_home_admink_pix2pix_datasets_alphabet1_train_trainCache.t7
Creating train metadata
serial batch:, 	0
table: 0x41b1d360
running "find" on each class directory, and concatenate all those filenames into a single file containing all image paths for a given class
now combine all the files to a single large file
now combine all the files to a single large file
load the large concatenated list of sample paths to self.imagePath
cmd..wc -L '/tmp/lua_kdsZSG' |cut -f1 -d' '
load the large concatenated list of sample paths to self.imagePath
cmd..wc -L '/tmp/lua_e80M1C' |cut -f1 -d' '
15 samples found..... 0/15 .....................] ETA: 0ms | Step: 0ms          
Updating classList and imageClass appropriately
 [=================== 1/1 =====================>] Tot: 0ms | Step: 0ms          
15 samples found..... 0/15 .....................] ETA: 0ms | Step: 0ms          
Updating classList and imageClass appropriately
 [=================== 1/1 =====================>] Tot: 0ms | Step: 0ms          
Cleaning up temporary files
Cleaning up temporary files
Dataset Size: 	50	
define model netG...	
define model netD...	
nn.gModule
nn.Sequential {
  [input -> (1) -> (2) -> (3) -> (4) -> (5) -> (6) -> (7) -> (8) -> (9) -> (10) -> (11) -> (12) -> (13) -> output]
  (1): nn.SpatialConvolution(6 -> 64, 4x4, 2,2, 1,1)
  (2): nn.LeakyReLU(0.2)
  (3): nn.SpatialConvolution(64 -> 128, 4x4, 2,2, 1,1)
  (4): nn.SpatialBatchNormalization (4D) (128)
  (5): nn.LeakyReLU(0.2)
  (6): nn.SpatialConvolution(128 -> 256, 4x4, 2,2, 1,1)
  (7): nn.SpatialBatchNormalization (4D) (256)
  (8): nn.LeakyReLU(0.2)
  (9): nn.SpatialConvolution(256 -> 512, 4x4, 1,1, 1,1)
  (10): nn.SpatialBatchNormalization (4D) (512)
  (11): nn.LeakyReLU(0.2)
  (12): nn.SpatialConvolution(512 -> 1, 4x4, 1,1, 1,1)
  (13): nn.Sigmoid
}
transferring to gpu...	
done	
THCudaCheck FAIL file=/home/admink/torch/extra/cutorch/lib/THC/generic/THCStorage.cu line=66 error=2 : out of memory
/home/admink/torch/install/bin/luajit: /home/admink/torch/install/share/lua/5.1/nn/Module.lua:309: cuda runtime error (2) : out of memory at /home/admink/torch/extra/cutorch/lib/THC/generic/THCStorage.cu:66
stack traceback:
	[C]: in function 'Tensor'
	/home/admink/torch/install/share/lua/5.1/nn/Module.lua:309: in function 'flatten'
	/home/admink/torch/install/share/lua/5.1/nn/Module.lua:326: in function 'getParameters'
	train.lua:445: in main chunk
	[C]: in function 'dofile'
	...mink/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:150: in main chunk
	[C]: at 0x00405d50

It only runs fine when dataset size is 3. i reduced the images size to 128*128 and could still train on 10 images maximum. I want to train the model on at least 500 images. How this error could be resolved?

**Comment by khaulahzia** [comment]
output of nvidia-smi
Wed Oct  4 00:03:06 2017       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 375.66                 Driver Version: 375.66                    |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  GeForce 930MX       Off  | 0000:01:00.0     Off |                  N/A |
| N/A   44C    P0    N/A /  N/A |    161MiB /  2002MiB |     10%      Default |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID  Type  Process name                               Usage      |
|=============================================================================|
|    0      1025    G   /usr/lib/xorg/Xorg                             105MiB |
|    0      1348    G   compiz                                          54MiB |
|    0      2861    G   /usr/lib/firefox/firefox                         1MiB |
+-----------------------------------------------------------------------------+

**Comment by phillipi** [comment]
hmm, I'm not quite sure why increasing the dataset size increases the memory use. It should only load images into gpu memory one batch at a time. It could be because small datasets go through epochs more quickly, and end up reaching [this line](https://github.com/phillipi/pix2pix/blob/master/train.lua#L439), where temporary variables are freed (`netG:clearState()`) more frequently.

In any case, it's running out of memory on [this line](https://github.com/phillipi/pix2pix/blob/master/train.lua#L445), so one fix would be to reduce the size of netD. However, there's probably a better way to manage the memory here.

**Comment by khaulahzia** [comment]
Thanks for the reply. Actually i m very new to deep learning and linux. It
would be great help if you can tell me how could the size of netD reduced?

**Comment by phillipi** [comment]
On the command line, you can pass, e.g., `ngf=32` and `ndf=32`. Those variables control the number of filters in `netG` and `netD` respectively. By default they are set to 64. Setting to 32 should use about half the memory. If that's still too much, you could try setting to 16, or any other small value.

**Comment by khaulahzia** [comment]
Would reducing the size of netD and netG affect the quality of training?

**Comment by phillipi** [comment]
Yeah it will probably make the results a bit worse but might still be acceptable.

**Comment by khaulahzia** [comment]
Ok thanks.

**Comment by khaulahzia** [comment]
DATA_ROOT=./datasets/alphabet1 name=blob_placement2 which_direction=AtoB
display=0 ngf=16 ndf=16 gpu=0 cudnn=0 batchsize=10 save_epoch_freq=5 th
train.lua
 worked for me. Thanks.
